<?php
/**
 * Product media data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 */
?>
<?php
$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');
?>
<p class="product-image">
    <?php
    $_img = '<img
        id="product-image-main"
        src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(265).'"
        alt="'.$this->escapeHtml($this->getImageLabel()).'"
        title="'.$this->escapeHtml($this->getImageLabel()).'"
    />';
    echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
</p>
<?php if (count($this->getGalleryImages()) > 1): ?>
    <div class="more-views">
        <h2><?php echo $this->__('More Views') ?></h2>
        <ul>
            <li>
                <a onclick="swapPhoto('<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(265) ?>')" />
                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(56); ?>" width="56" height="56" alt="<?php echo $this->escapeHtml($this->getImageLabel()) ?>" />
                </a>
            </li>
            <?php foreach ($this->getGalleryImages() as $_image): ?>
                <li>
                    <a onclick="swapPhoto('<?php echo $this->helper('catalog/image')->init($_product, 'image', $_image->getFile())->resize(265) ?>')" />
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $_image->getFile())->resize(56); ?>" width="56" height="56" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" />
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
<script>
    var swapPhoto = function(src){
        $('product-image-main').setAttribute('src', src);
    };
</script>